export const categoryDisplayName: Record<string, string> = {
  'geral': 'Geral',
  'maus tratos': 'Maus Tratos',
  'abandono presenciado': 'Abandono Presenciado',
  'animal apareceu na rua': 'Animal Apareceu na Rua',
  'ajuda animal comunitario': 'Ajuda Animal Comunitário',
  'saude animal': 'Saúde Animal',
  'castracao eletiva': 'Castração Eletiva',
  'castracao emergencial': 'Castração Emergencial',
  'animais nao domiciliados': 'Animais Não Domiciliados',
  'animal desaparecido': 'Animal Desaparecido',
  'animal para ser adotado': 'Animal para ser Adotado',
  'adocao de animais': 'Adoção de Animais',
  'animal grande porte': 'Animal Grande Porte',
  'animal atropelado': 'Animal Atropelado',
  'cuidados animais': 'Cuidados Animais',
  'animais silvestres': 'Animais Silvestres',
  'equipamentos': 'Equipamentos',
}
